permalink: none
exclude: [README.rdoc, Rakefile]
include: [.well-known]
environments:
  stage:
    url: http://vp.com.ve/edgar.staging
    remote:
      connection: odin@gonzalez.io
      path: /home/odin/public_html/edgar.staging
  production:
    url: http://www.gonzalez.io
    remote:
      connection: odin@gonzalez.io
      path: /home/odin/public_html/gonzalez