permalink: none
exclude: [README.rdoc, Rakefile]
environments:
  stage:
    url: http://vp.com.ve/edgar.staging
    remote:
      connection: odin@edgar.com.ve
      path: /home/odin/public_html/edgar.staging
  production:
    url: http://edgar.com.ve
    remote:
      connection: odin@edgar.com.ve
      path: /home/odin/public_html/edgar